name: (Internal) Tech Debt Template
description: Intended to help create internal tech debt change.
title: "[Tech Debt]: "
labels: ["kind/tech-debt"]
body:
  - type: dropdown
    id: deploy-type
    attributes:
      label: Type
      description: What kind of tech debt is it?
      multiple: true
      options:
        - General Tech Debt (eg. Improve the way something exists today)
        - Dev Efficiency (eg. CI improvements, issue templates, etc)
        - Infrastructure (eg. Add web sockets)
        - Quality (eg. tests)
    validations:
      required: true
  - type: input
    id: source
    attributes:
      label: Source
      description: Where did you find this issue?
      placeholder: main / feature branch x / incubation / etc
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What should we improve?
    validations:
      required:
        true
  - type: textarea
    id: why
    attributes:
      label: Why?
      description: What value does this bring / what is it fixing?
    validations:
      required:
        true
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: |
        Additional information. Suggested topics:
        - Initial investigation
        - Known impact this will cause
        - Anything else you want to add
    validations:
      required:
        false
